### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by holger81** [jbasen/Crestron-SmartSlydr#1]
Hi Jay,

I recently got myself a SmartSlydr and am about to integrate with HomeAssistant. Your work here provided a lot of help for interfacing with Lycheethings. 

In your article on restechtoday.com you mention that Lycheethings had a good API documentation. I was wondering where to find that?

Concretely, I am suspecting that there is a cloud push method somewhere? Otherwise issues with the window opening would be difficult to directly see in the app...

Thanks in advance, 
 Holger

**Comment by jbasen** [comment]
Hi Holger,
Thanks for your message.  The API was a pdf sent to me by the folks at SmartSlydr.  So, I'm not comfortable passing it along without their permission.  However, if you contact them and tell them what you are doing I expect they would pass it along.  
That being said the driver here on my GitHub implements everything in the version of the API that they sent me.  There wasn't a cloud push method.  The only way to get status was to poll the API.  
Hope this helps

**Comment by holger81** [comment]
Hi,

ah, thanks for the fast reply. I will reach out to them directly. Would be great if there was a cloud-push or even better local access possibility... 

But knowing that you implemented everything they made available to you already helps a lot, thanks a bunch!
